{% set name = "xmod" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmod-{{ version }}.tar.gz
  sha256: 98b2e7e8e659c51b635f4e98faf3fa1f3f96dab2805f19ddd6e352bbb4d23991

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - xmod
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rec/xmod
  summary: 🌱 Turn any object into a module 🌱
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicornk
