{% set name = "xmod" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmod-{{ version }}.tar.gz
  sha256: b40b2a54d56684b01eb9627892b0c179918e8ef0bd4d7f3bac7a3fdba11cd6e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - xmod
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rec/xmod
  summary: 🌱 Turn any object into a module 🌱
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicornk
