schema_version: 1

context:
  version: "1.10.0"

package:
  name: xmod
  version: ${{ version }}

source:
  url: https://github.com/rec/xmod/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ed8b42a59ff9bcd372df0ffd10cbde717207f5ab44d6614433dd0f438ce50b36

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - xmod
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - script:
      - pytest -vvv test/
    requirements:
      run:
        - pytest
    files:
      source:
        - test/

about:
  summary: 🌱 Turn any object into a module 🌱
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rec/xmod

extra:
  recipe-maintainers:
    - nicornk
    - jsmolic
